// What the ribbon shows: tabs → groups → commands, with the hover help for each command.
// Behaviour comes from bindings (shell/core.tsx) registered by the app and the active document.
export type Item =
  | { t: "L" | "S"; id: string; label: string; icon: string; h: string; r?: string; key?: string }
  | { t: "F"; id: string; label: string; kind: "select" | "spin" | "text"; h: string; w?: number; step?: number }
  | { t: "C"; id: string; label: string; h: string };
export interface Group { name: string; when?: string; items: (Item | Item[])[] }
export interface Tab { name: string; contextual?: string; groups: Group[] }

const L = (id: string, label: string, icon: string, h: string, r?: string, key?: string): Item => ({ t: "L", id, label, icon, h, r, key });
const S = (id: string, label: string, icon: string, h: string, r?: string, key?: string): Item => ({ t: "S", id, label, icon, h, r, key });
const F = (id: string, label: string, kind: "select" | "spin" | "text", h: string, w?: number, step?: number): Item => ({ t: "F", id, label, kind, h, w, step });
const C = (id: string, label: string, h: string): Item => ({ t: "C", id, label, h });

const WHEN = {
  scene: "Open a scene (Explorer ▸ Scenes) to use this.",
  capture: "Open New capture (Capture ▸ New capture) to use this.",
  splat: "Open a scene or New capture to use this.",
  course: "Open the course editor (Explorer ▸ Courses) to use this.",
  kf: "Select a keyframe in the course editor.",
  cohortList: "Open SV-Net ▸ New cohort to use this.",
  cohort: "Open a cohort (Explorer ▸ Cohorts) to use this.",
  sv: "Open SV-Net (new cohort) or a cohort to use this.",
  monitor: "Open the Monitor (Jobs) or a job to use this.",
  config: "Open a config (Explorer ▸ Configs) to use this.",
};

export const TABS: Tab[] = [
  { name: "Home", groups: [
    { name: "Context", items: [[F("home.scene", "Scene", "select", "Scene for the Course and Capture & Splat tabs. Picking one opens it."),
      F("home.course", "Course", "select", "Opens this course in the course editor, over the chosen scene."),
      F("home.cohort", "Cohort", "select", "Opens this SV-Net cohort.")]] },
    { name: "Queue", items: [
      L("run", "Run", "run", "Run the active document's job: fly the course, run the scene's steps, continue the cohort, queue the capture. Joins the queue; one GPU job runs at a time.", "the document's script, through figs_env.sh", "F5"),
      L("job.cancel", "Cancel", "cancel", "Stop the running job: SIGTERM to its whole process group, SIGKILL after 10 s. Its step markers stay, so Run resumes where it stopped.", "POST /api/jobs/{id}/cancel", "Shift+F5"),
      [S("job.rerun", "Re-run", "rerun", "Queue the focused job (Output ▸ Queue, or the last finished one) again with the same parameters."),
        S("queue.pause", "Pause queue", "pause", "Let the running job finish but start nothing new."),
        S("queue.clear", "Hide finished", "delete", "Hide succeeded and cancelled jobs from the queue lists. Nothing is deleted.")]] },
    { name: "Machine", items: [[S("m.gpu", "GPU", "gpu", "Live nvidia-smi: memory, utilisation, temperature. Opens the Monitor."),
      S("m.disk", "Disk", "disk", "Free space under project_root. Rollout data needs ~6 GB (data_alpha) to ~265 GB (data_gamma)."),
      S("m.profile", "Profile", "machine", "Machine profile in use (ui/machines/<host>.toml): paths, GPU, defaults.")]] },
    { name: "Recent", items: [[S("r.flight", "Last flight", "video", "Opens the scene of the most recent flight run record."),
      S("r.cohort", "Last cohort", "cohort", "Opens the most recently changed SV-Net cohort."),
      S("r.job", "Last job", "job", "Opens the most recent job and its log.")]] },
    { name: "Help", items: [L("help.docs", "Help", "help", "What each part of the window does, and where the handoff docs are.", "", "F1"),
      [S("help.keys", "Shortcuts", "docs", "All keyboard shortcuts."), S("help.about", "About", "info", "Galley, the backend it talks to, and the machine profile.")]] },
  ] },
  { name: "Capture & Splat", groups: [
    { name: "Capture", items: [L("cap.new", "New capture", "camera", "Start a scene from a phone video: name check, probe, transcode, ArUco check, SfM and training, up to the step you choose.", "figs_pipeline.py --scene <name> --video <file>"),
      [S("cap.upload", "Upload video", "upload", "Send a phone video from this computer to the host's video_captures/: 8 MB chunks, checksummed where the browser allows, resumable if the connection drops (choose the same file again). Dropping a video anywhere on the window does the same. FiGS never reads that folder; transcode copies it.", "POST/PUT /api/uploads"),
        S("cap.probe", "Probe", "probe", "Codec, resolution, fps and a variable-frame-rate warning, before anything else runs.", "figs_pipeline.py --only probe"),
        S("cap.name", "Name check", "search", "FiGS matches scenes by substring: 'intellisense' collides with 'intellisense_02'. Shows the result of the check.")],
      [S("cap.drive", "Google Drive", "cloud", "Pick videos in your Google Drive; the host downloads them itself (fast lab link, nothing goes through this computer) and keeps going if this tab closes. Sign-in lets Galley read only the files you pick. First use asks for the Google Cloud client ID, API key and project number.", "POST /api/drive/imports")]] },
    { name: "Markers", when: WHEN.capture, items: [[F("cap.marker_id", "Marker ID", "spin", "ArUco marker id taped in the room (DICT_4X4_50)."),
      F("cap.marker_len", "Length (m)", "spin", "Black square side, tape-measured, in metres. Nothing downstream can check it: the whole splat scales with it.", 72, 0.001),
      F("cap.marked", "Marked frames", "spin", "How many frames must show the marker (--num-marked).")],
      L("cap.aruco", "ArUco check", "marker", "Queue the capture up to the ArUco step: detections per 10 s window against 3× marked frames.", "figs_pipeline.py --stop-after aruco")] },
    { name: "Sampling", when: WHEN.capture, items: [[F("cap.images", "Images", "spin", "Frames sampled for SfM (--num-images). 600 → ~180k match pairs, about 4× the 300-image time."),
      F("cap.video", "Video", "select", "Phone video in video_captures/ on the host, or one still uploading (the capture can be queued to start when it arrives)."),
      F("cap.stop", "Stop after", "select", "Last step of the first run. New rooms normally stop after bounds: a course needs the splat's frame.")]] },
    { name: "Reconstruct", when: WHEN.splat, items: [L("splat.sfm", "SfM", "sfm", "hloc + COLMAP structure-from-motion, aligned to the marker. Cached: retraining never repeats it.", "figs_pipeline.py --only sfm"),
      L("splat.train", "Train", "splat", "Train the Gaussian splat (nerfstudio splatfacto) from the SfM result, then verify.", "figs_pipeline.py --from train --stop-after verify --archive-old"),
      [F("splat.downscale", "Downscale", "spin", "--downscale: image downscale for training (empty = auto, ≤1600 px)."),
        F("splat.iters", "Iterations", "spin", "--train-iters (empty = 30000)."),
        F("splat.cache", "Image cache", "select", "--cache-images: cpu keeps training images out of VRAM (5.2 GB → 2.4 GB on backroom).")]] },
    { name: "Models", when: WHEN.scene, items: [L("splat.archive", "Archive", "archive", "Move the active training run to gsplats/workspace/_archive/<scene>/ and clear verify/simulate/validate. FiGS needs exactly one active model.", "POST /api/scenes/{scene}/models/{run}/archive"),
      L("splat.promote", "Promote", "promote", "Make the newest complete archived run active again (archiving the current one). Refused while a job for this scene is queued or running.", "POST …/models/{run}/promote"),
      [S("splat.viewer", "Viewer", "viewer", "ns-viewer on the active model (:7007). It holds ~4.6 GB, so it will run as a queued GPU job."),
        S("splat.curve", "Training curve", "chart", "Scroll to the training curve of the active run."),
        S("splat.verify", "Verify", "validate", "Registration rate (fails under 90 %), sparse points, reprojection error, checkpoint.", "figs_pipeline.py --only verify --redo verify")]] },
    { name: "Steps", when: WHEN.scene, items: [[F("steps.from", "From", "select", "--from: first step to run."), F("steps.stop", "Stop after", "select", "--stop-after: last step."),
      C("steps.redo", "Redo them", "--redo every step in the range, even if its marker says done.")],
      L("steps.run", "Run steps", "continue", "Run the chosen step range for this scene.", "figs_pipeline.py --scene <scene> --from … --stop-after …")] },
  ] },
  { name: "Course", groups: [
    { name: "File", when: WHEN.course, items: [L("course.newloop", "New loop", "loop", "Four-corner loop inside the recommended waypoint box: a starting course for a new room."),
      [S("file.save", "Save", "save", "Save as floats in upstream's layout and mirror to figs/sousvide_overlay.", "PUT /api/configs/courses/{name}", "Ctrl+S"),
        S("course.saveas", "Save as", "saveas", "Save under a new name. Upstream names (circuit, traverse…) ask first: a re-clone restores them."),
        S("edit.undo", "Undo", "undo", "Undo the last edit (200 steps).", "", "Ctrl+Z")],
      [F("course.scene", "Scene", "select", "Scene whose point cloud and camera path the course is drawn over."),
        F("course.name", "Course", "select", "Course file to edit (SousVide/configs/courses)."),
        S("course.lint", "Lint", "validate", "Find integer cells FiGS would misread (0 instead of 0.0).", "GET /api/courses/{name}/lint")]] },
    { name: "Edit", when: WHEN.course, items: [L("tool.move", "Move", "move", "Drag a keyframe with the gizmo; only its fixed axes move.", "", "M"),
      L("tool.yaw", "Yaw", "yaw", "Rotate a keyframe about z (down). Kept unwrapped: consecutive values within π.", "", "R"),
      L("tool.add", "Add", "addpt", "Click the tinted plane to insert a keyframe after the selected one, at its altitude.", "", "A"),
      L("tool.goal", "Goal", "goal", "Place or select the semantic-goal marker (label + position). Saved as semantic_goal; FiGS ignores it.")] },
    { name: "Preview", when: WHEN.course, items: [L("prev.run", "Preview", "preview", "Minimum snap through the keyframes at the file's times (FiGS MinTimeSnap), ~0.5 s. Runs by itself while Live is on.", "course_tools.py preview --mode fixed", "F6"),
      L("prev.retime", "Re-time", "retime", "Re-time like the expert: Viper's kT re-optimises segment times, as the real flight does. 20 s – 2 min.", "course_tools.py preview --mode expert"),
      [C("prev.live", "Live", "Re-solve 0.6 s after each edit."), S("prev.play", "Play", "play", "Fly the preview in real time: the drone moves along the path and the charts' cursor follows."),
        F("prev.speed", "Speed", "select", "Playback speed.", 60)]] },
    { name: "Checks", when: WHEN.course, items: [[F("chk.gap", "Min gap (m)", "spin", "Smallest allowed gap between the drone and the scenery (between its bounding sphere and the k-th nearest SfM point).", 60, 0.05),
      F("chk.k", "k-th point", "spin", "Clearance uses the k-th nearest SfM point so a lone outlier does not count.", 60),
      C("chk.body", "Drone size", "Subtract the drone's bounding sphere (guards included) from every distance.")]] },
    { name: "Show", when: WHEN.course, items: [L("view.splat", "Splat", "splat", "Show the trained Gaussian splat — what the drone's camera sees in FiGS — instead of the SfM points. The first time, the active checkpoint is exported for the browser (up to 1 M most visible Gaussians, about 30 MB; tens of seconds), then it is cached until the model changes.", "course_tools.py splat --ckpt <active run> (CPU)"), [S("view.points", "Points", "points", "SfM sparse point cloud."), S("view.alt", "Altitude", "altitude", "Colour points by altitude instead of RGB."),
      S("view.cam", "Camera path", "campath", "Where the phone went during capture.")],
      [S("view.boxes", "Boxes", "boxes", "Camera box (where the camera went, not free space) and the waypoint box."), S("view.drone", "Drone", "drone", "Your airframe at true scale, on the cursor with FiGS's attitude."),
        F("view.psize", "Point size", "spin", "Point sprite size in metres.", 60, 0.005)],
      [F("view.navspeed", "Key speed", "select", "Speed of arrow-key flying in the 3D view (it also scales with how far you are from the orbit centre; Shift = 3×). Arrows fly level, PgUp/PgDn or E/Q go up/down, Ctrl+arrows look around, +/− move closer/farther, F centres on the selection, Home resets the view.", 64)]] },
    { name: "Fly", when: WHEN.course, items: [[F("fly.expert", "Expert", "select", "Expert pilot (MPC) config."), F("fly.frame", "Frame", "select", "Vehicle frame: mass and thrust coefficient."),
      F("fly.method", "Method", "text", "Evaluation method config.")], [C("fly.outside", "Allow outside", "Fly even if keyframes leave the captured volume (renders mush outside it).")],
      L("fly.go", "Fly", "fly", "Save, then fly the expert through the splat and check the video.", "figs_pipeline.py --from course --stop-after record --redo course simulate validate", "F5")] },
    { name: "Window", items: [L("view.fullscreen", "Full screen", "fullscreen", "Give the whole screen to the active document: hides the title bar, Explorer, document tabs and status bar, collapses the ribbon (click a tab to use it for one command) and enters browser full screen. Properties and Output can be shown from the strip at the top. Esc or Ctrl+Shift+F leaves.", "", "Ctrl+Shift+F"),
      [S("tile.view", "Maximize 3D view", "maximize", "The 3D view fills the workspace. Click again, or press Esc, to restore the tiles."),
        S("tile.kf", "Maximize keyframes", "matrix", "The keyframe table fills the workspace."),
        S("tile.charts", "Maximize charts", "chart", "The preview's charts fill the workspace, each as tall as the space allows.")],
      [S("tile.reset", "Reset tiles", "restore", "Restore the default sizes of the 3D view, keyframe and chart tiles. Drag the splitters between tiles to resize them; double-click a splitter to reset it.")]] },
  ] },
  { name: "SV-Net", groups: [
    { name: "Cohort", items: [L("sv.new", "New cohort", "cohort", "Scene, courses, rollout method, students, epochs and evaluation, with a disk estimate before anything flies.", "svnet_pipeline.py --cohort <name> …"),
      [F("sv.open", "Open", "select", "Open an existing cohort."), S("sv.duplicate", "Duplicate", "copy", "A new cohort with this one's settings (e.g. p4_smoke → p4_beta with data_beta)."),
        S("sv.preflight", "Preflight", "preflight", "Imports, configs, one model in the scene, integer course cells, data size against free disk. Flies nothing.", "svnet_pipeline.py --only preflight")]] },
    { name: "Data", when: WHEN.cohortList, items: [[F("sv.method", "Method", "select", "Rollout dataset size: data_alpha ~6 GB · data_beta ~88 GB · data_gamma ~265 GB per course."),
      F("sv.scene", "Scene", "select", "Scene with exactly one trained model."), F("sv.nro", "Rollouts/save", "spin", "Nro_ds: rollouts per saved file (RAM per save ~2.8 GB at 50).")],
      [C("sv.compress", "Compress", "use_compress: store rollouts compressed."), F("sv.subsample", "Subsample", "spin", "Observation subsample ratio.", 60, 0.1),
        S("sv.estimate", "Size estimate", "disk", "Preflight only: rollouts, samples and GB for this setting against free disk.")]] },
    { name: "Train", when: WHEN.sv, items: [[F("sv.hist", "histNet epochs", "spin", "Epochs for the history network."), F("sv.comm", "commNet epochs", "spin", "Epochs for the command network."),
      F("sv.batch", "Batch", "spin", "Batch size. 32 if commNet runs out of memory.")],
      [F("sv.lr", "LR", "text", "Learning rate (empty = upstream default)."), F("sv.eval", "In-loop eval", "select", "Evaluation flights every save; eval_nominal flies 10 per save (~6.8 GB with commNet)."),
        C("sv.fresh", "Fresh networks", "Archive existing networks first; otherwise sousvide keeps training what is on disk.")]] },
    { name: "Run", when: WHEN.cohort, items: [L("sv.continue", "Continue", "continue", "Resume the cohort from its first unfinished step; settings come from the cohort.", "svnet_pipeline.py --cohort <cohort>", "F5"),
      [F("sv.from", "From", "select", "First step (empty = first unfinished)."), F("sv.to", "To", "select", "Last step."), C("sv.redo", "Force redo", "Re-run the From step even if done; everything after it re-runs too.")]] },
    { name: "Evaluate", when: WHEN.cohort, items: [L("sv.deploy", "Deploy", "deploy", "Fly expert and students in FiGS: per-point tracking error next to upstream's TTE/PP, plus videos.", "svnet_pipeline.py --only deploy --redo deploy"),
      L("sv.compare", "Compare", "compare", "Side-by-side metrics, losses and videos of two cohorts."),
      [S("sv.vexpert", "Expert video", "video", "The expert's last deployment rollout."), S("sv.vstudent", "Student video", "video", "The first student's last deployment rollout."),
        S("sv.csv", "Export CSV", "save", "The evaluation table as CSV.")]] },
  ] },
  { name: "Jobs", groups: [
    { name: "Queue", items: [L("job.cancel", "Cancel", "cancel", "Stop the focused or running job (its whole process group).", "", "Shift+F5"),
      L("job.rerun", "Re-run", "rerun", "Queue the focused job again with the same parameters."),
      [S("queue.pause", "Pause queue", "pause", "Start nothing new after the running job."), S("queue.up", "Move up", "chevron", "Run this queued job earlier."),
        S("queue.clear", "Hide finished", "delete", "Hide finished jobs in the queue lists.")]] },
    { name: "Filter", items: [[F("jobs.kind", "Kind", "select", "figs · svnet · selftest"), F("jobs.scene", "Scene", "select", "Only jobs for one scene."),
      F("jobs.status", "Status", "select", "queued · running · succeeded · failed · cancelled · interrupted")]] },
    { name: "Log", items: [L("log.follow", "Follow", "follow", "Keep logs scrolled to the newest line."),
      [S("log.wrap", "Wrap lines", "density", "Wrap long lines instead of scrolling sideways."), S("log.save", "Save log", "save", "Download the focused job's log."),
        S("job.selftest", "Self-test", "job", "Queue a harmless 20 s job to check the queue, log streaming and cancel.")]] },
    { name: "Compare", when: WHEN.monitor, items: [L("runs.diff", "Diff runs", "diff", "Diff two flight run records (runs/*.json) side by side."),
      [S("runs.snapshot", "Parameters", "config", "The focused job's exact parameters and command line."), S("runs.records", "Run records", "log", "List of flight run records (runs/<scene>_<ts>.json).")]] },
  ] },
  { name: "Configs", groups: [
    { name: "Family", items: [[S("cfg.f.captures", "Captures", "camera", "configs/captures: intrinsics and ArUco extractor settings."), S("cfg.f.courses", "Courses", "route", "configs/courses: keyframes."),
      S("cfg.f.pilots", "Pilots", "network", "configs/pilots: experts (Viper) and students (Maverick, Iceman).")],
      [S("cfg.f.frames", "Frames", "drone", "configs/frames: mass, thrust coefficient, camera."), S("cfg.f.methods", "Methods", "steps", "configs/methods: data_* and eval_*."),
        S("cfg.f.nnio", "NNIO", "json", "configs/nnio: network inputs/outputs.")]] },
    { name: "Edit", when: WHEN.config, items: [L("cfg.validate", "Validate", "validate", "Check against the Pydantic model without saving; refuses anything that would not round-trip.", "POST /api/configs/{family}/validate", "F7"),
      L("file.save", "Save", "save", "Validate and write. Captures, courses and pilots are mirrored to figs/sousvide_overlay.", "PUT /api/configs/{family}/{name}", "Ctrl+S"),
      [S("cfg.revert", "Revert", "undo", "Discard unsaved edits."), S("cfg.duplicate", "Duplicate", "copy", "Save as a new variant (e.g. Viper_slow with a smaller kT)."), S("cfg.format", "Format", "json", "Pretty-print the JSON.")]] },
    { name: "Overlay", when: WHEN.config, items: [L("cfg.mirror", "Mirror", "overlay", "Saving a capture, course or pilot copies it to figs/sousvide_overlay, so it survives a SousVide re-clone. Saves now."),
      [S("cfg.diffup", "Diff upstream", "diff", "Compare with the upstream file at the pinned commit."), S("cfg.restore", "Restore", "rerun", "Restore from the overlay.")]] },
  ] },
  { name: "View", groups: [
    { name: "Panes", items: [[C("view.explorer", "Explorer", "Scenes, courses, cohorts, configs and jobs tree."), C("view.properties", "Properties", "Details of whatever is selected."),
      C("view.output", "Output", "Live log, queue, problems and GPU, docked at the bottom.")], [C("view.status", "Status bar", "Machine, GPU, disk and queue."),
      C("view.minribbon", "Minimize ribbon", "Show only the tab names (Ctrl+F1)."), S("view.reset", "Reset layout", "panes", "Restore the default panes and density.")]] },
    { name: "Layout", items: [L("layout.edit", "Edit", "layout", "All panes: for course editing and configs."), L("layout.train", "Train", "chart", "Hide the Explorer and Properties: wide charts while training."),
      L("layout.monitor", "Monitor", "gauge", "Opens the Monitor with the Output panel hidden: queue, log and GPU large.")] },
    { name: "Density", items: [[S("density.compact", "Compact", "density", "22 px rows, 12 px text."), S("density.comfortable", "Comfortable", "density", "26 px rows."),
      S("density.large", "Larger text", "search", "13 px text.")]] },
    { name: "Window", items: [[S("win.float", "New window", "copy", "Open the active document in a new browser window."), S("win.closeall", "Close others", "close", "Close every document except the active one."),
      S("win.split", "Split right", "panes", "Show two documents side by side.")], [S("view.fullscreen", "Full screen", "fullscreen", "Give the whole screen to the active document: hides the title bar, Explorer, document tabs and status bar, collapses the ribbon (click a tab to use it for one command) and enters browser full screen. Properties and Output can be shown from the strip at the top. Esc or Ctrl+Shift+F leaves.", "", "Ctrl+Shift+F")]] },
  ] },
  { name: "Keyframe Tools", contextual: "ctx.keyframe", groups: [
    { name: "Keyframe", when: WHEN.kf, items: [L("kf.insert", "Insert after", "insert", "New pass-through keyframe between this one and the next (position fixed, derivatives free).", "", "Ins"),
      L("kf.delete", "Delete", "delete", "Remove the keyframe (a course keeps at least 2).", "", "Del"),
      [S("kf.up", "Move up", "chevron", "Swap order with the previous keyframe; times stay increasing."), S("kf.down", "Move down", "chevdown", "Swap with the next keyframe."),
        S("kf.matrix", "Matrix", "matrix", "Show the 4 × 5 derivative matrix in Properties.")]] },
    { name: "Constraints", when: WHEN.kf, items: [[S("kf.stop", "Stop here", "pause", "Pin velocity to 0 on every axis (start/end of a course)."), S("kf.free", "Free derivatives", "fresh", "Clear every derivative cell; keep position."),
      S("kf.fix", "Fix position", "pin", "Fix free x, y, z at the value shown (the solver's, after a preview).")]] },
    { name: "Timing", when: WHEN.kf, items: [[F("kf.t", "t (s)", "spin", "Keyframe time. With Viper's kT it is only the solver's starting guess.", 64, 0.1),
      S("kf.solved", "Write solved times", "retime", "Copy the expert's re-timed values into the file so file and flight agree (after Re-time).")]] },
  ] },
  { name: "Model Tools", contextual: "ctx.model", groups: [
    { name: "Model", when: WHEN.scene, items: [L("splat.promote", "Promote", "promote", "Make the newest complete archived run active."), L("splat.archive", "Archive", "archive", "Archive the active run."),
      [S("splat.viewer", "Viewer", "viewer", "Open in ns-viewer (queued GPU job)."), S("splat.curve", "Training curve", "chart", "TensorBoard scalars of the active run."),
        S("splat.export", "Export splat", "save", "ns-export gaussian-splat (for an in-browser splat view).")]] },
  ] },
];
export const SHORTCUTS: [string, string][] = [
  ["F5", "Run the active document's job (fly / run steps / continue / queue)"], ["Shift+F5", "Cancel the running job"],
  ["Ctrl+S", "Save (course, config)"], ["Ctrl+Z", "Undo (course editor)"], ["F6", "Preview the course"], ["F7", "Validate the config"],
  ["Ctrl+F1", "Minimize / restore the ribbon"], ["F1", "Help"], ["M / R / A", "Course editor tools: move, yaw, add"],
  ["Del", "Delete the selected keyframe"], ["Ctrl+Shift+F", "Full screen (any document)"],
  ["Esc", "Deselect; restore a maximized tile; leave full screen"],
  ["Arrows", "Course 3D view: fly forward/back, sideways (level)"], ["PgUp / PgDn, E / Q", "Course 3D view: up / down"],
  ["Ctrl+arrows", "Course 3D view: look around"], ["+ / −", "Course 3D view: closer to / farther from the orbit centre"],
  ["Shift (held)", "Course 3D view: 3× faster"], ["F / Home", "Course 3D view: centre on the selection / default view"],
];
